# Generated by Django 4.1.6 on 2023-02-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_couponhistory_coupons_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.user'),
        ),
    ]
