# Generated by Django 4.1.6 on 2023-02-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_coupons_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downUserId', to='administrator.user')),
                ('from_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromUserId', to='administrator.user')),
            ],
        ),
    ]
