# Generated by Django 4.1.6 on 2023-02-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_rename_down_user_id_downhistory_down_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downhistory',
            name='down_user',
            field=models.IntegerField(null=True, verbose_name='down_user id'),
        ),
        migrations.AlterField(
            model_name='downhistory',
            name='from_user',
            field=models.IntegerField(null=True, verbose_name='from_user id'),
        ),
    ]
