# Generated by Django 4.1.6 on 2023-02-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_downhistory_down_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updatedBy',
        ),
    ]
